<!-- que esta mal de este ejercicio??? -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE favoritos [
  <!ELEMENT favoritos (marcador)>
  <!ELEMENT marcador (nombre, uri)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT uri (#PCDATA)>
]>

<marcadores>
  <marcador>
    <nombre>W3C</nombre>
    <uri>http://www.w3.org/</uri>
  </marcador>
  <marcador>
    <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
    <uri>http://www.whatwg.org/</uri>
  </marcador>
</marcadores>


solución:
Según la DTD, el elemento raíz es <favoritos>, pero en el documento el elemento raíz es <marcadores>.Para corregirlo, habría que cambiar el nombre del elemento raíz de <favoritos> a <marcadores> y añadir la definición de ese elemento.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
  <!ELEMENT marcadores (marcador+)>
  <!ELEMENT marcador (nombre, uri)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT uri (#PCDATA)>
]>

<marcadores>
  <marcador>
    <nombre>W3C</nombre>
    <uri>http://www.w3.org/</uri>
  </marcador>
  <marcador>
    <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
    <uri>http://www.whatwg.org/</uri>
  </marcador>
</marcadores>